package shapes;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author x13114352
 */
public class GameGUI extends javax.swing.JFrame {

    CustButton myButton = new CustButton();
    CustButton myButton1 = new CustButton();
   

    int score = 0;
    Player obj = new Player();

    Connection conn;
    DBManager manager;

    String dbServer = "jdbc:mysql://mysql1.gear.host/";
    String dbName = "shapersdb";
    String dbUser = "shapers";
    String dbPass = "shapers!";
    String driver = "com.mysql.jdbc.Driver";

    /**
     * Creates new form gameGUI
     */
    public GameGUI() {
        super("Shapes Game");
        initComponents();
        manager = new DBManager();

        try {
            conn = DriverManager.getConnection(dbServer + dbName, dbUser, dbPass);
            manager.setConn(conn);
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());

        }

        //imageIcon 
        ImageIcon image = new ImageIcon(getClass().getResource("/images/sphere-red.png"));

        myButton.ImageName = "Red Circle";
        myButton.setName("circleLb");
        myButton.setBounds(0, 0, 190, 150);
        myButton.setOpaque(false);
        myButton.setContentAreaFilled(false);
        myButton.setBorderPainted(false);
        myButton.setIcon(image);
        lPane.add(myButton);

        ImageIcon image2 = new ImageIcon(getClass().getResource("/images/square-green.png"));

        myButton1.ImageName = "Green Square";
        myButton1.setName("circleLb");
        myButton1.setBounds(0, 0, 190, 150);
        myButton1.setOpaque(false);
        myButton1.setContentAreaFilled(false);
        myButton1.setBorderPainted(false);
        myButton1.setIcon(image2);
        lPane2.add(myButton1);

    }

    public void setPlayer(Player p) {
        this.obj = p;
    }

    public void updateScore(Player s) {
        String query = "UPDATE Player SET gamerscore = " + s.getGamercore() + ""
                + " where pid=" + s.getPid() + ";";
        boolean upd = manager.UPDATE_QUERY(query);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TitleBtn = new javax.swing.JLabel();
        EndBTn = new javax.swing.JButton();
        lPane2 = new javax.swing.JLayeredPane();
        scoreLbl = new javax.swing.JLabel();
        score1Lbl = new javax.swing.JLabel();
        lPane = new javax.swing.JLayeredPane();
        gTriangleBtn = new javax.swing.JButton();
        PurpleTriangleBtn = new javax.swing.JButton();
        RedSquareBtn = new javax.swing.JButton();
        GreenCircleBtn = new javax.swing.JButton();
        rCircleBtn = new javax.swing.JButton();
        displayLbl = new javax.swing.JLabel();
        bSquareBtn = new javax.swing.JButton();
        bcGroundLbl = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(630, 630));
        jPanel1.setLayout(null);

        TitleBtn.setBackground(new java.awt.Color(255, 255, 255));
        TitleBtn.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        TitleBtn.setText("Level 1");
        jPanel1.add(TitleBtn);
        TitleBtn.setBounds(190, 20, 120, 30);

        EndBTn.setBackground(new java.awt.Color(255, 255, 255));
        EndBTn.setText("End Game");
        EndBTn.setOpaque(false);
        EndBTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndBTnActionPerformed(evt);
            }
        });
        jPanel1.add(EndBTn);
        EndBTn.setBounds(360, 280, 100, 23);

        javax.swing.GroupLayout lPane2Layout = new javax.swing.GroupLayout(lPane2);
        lPane2.setLayout(lPane2Layout);
        lPane2Layout.setHorizontalGroup(
            lPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        lPane2Layout.setVerticalGroup(
            lPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel1.add(lPane2);
        lPane2.setBounds(70, 80, 140, 110);

        scoreLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        scoreLbl.setText("Score:");
        jPanel1.add(scoreLbl);
        scoreLbl.setBounds(320, 10, 70, 40);

        score1Lbl.setBackground(new java.awt.Color(0, 0, 0));
        score1Lbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(score1Lbl);
        score1Lbl.setBounds(400, 20, 40, 20);

        lPane.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout lPaneLayout = new javax.swing.GroupLayout(lPane);
        lPane.setLayout(lPaneLayout);
        lPaneLayout.setHorizontalGroup(
            lPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        lPaneLayout.setVerticalGroup(
            lPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(lPane);
        lPane.setBounds(270, 90, 140, 100);

        gTriangleBtn.setBackground(new java.awt.Color(255, 255, 255));
        gTriangleBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        gTriangleBtn.setForeground(new java.awt.Color(0, 204, 51));
        gTriangleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/GreenTriangle.png"))); // NOI18N
        gTriangleBtn.setText("Green Triangle");
        gTriangleBtn.setOpaque(false);
        gTriangleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gTriangleBtnActionPerformed(evt);
            }
        });
        jPanel1.add(gTriangleBtn);
        gTriangleBtn.setBounds(340, 240, 110, 20);

        PurpleTriangleBtn.setBackground(new java.awt.Color(255, 255, 255));
        PurpleTriangleBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PurpleTriangleBtn.setForeground(new java.awt.Color(102, 0, 102));
        PurpleTriangleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Purple Triangle.png"))); // NOI18N
        PurpleTriangleBtn.setText("Purple Triangle");
        PurpleTriangleBtn.setOpaque(false);
        PurpleTriangleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurpleTriangleBtnActionPerformed(evt);
            }
        });
        jPanel1.add(PurpleTriangleBtn);
        PurpleTriangleBtn.setBounds(340, 210, 110, 20);

        RedSquareBtn.setBackground(new java.awt.Color(255, 255, 255));
        RedSquareBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RedSquareBtn.setForeground(new java.awt.Color(255, 0, 0));
        RedSquareBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Red Square.png"))); // NOI18N
        RedSquareBtn.setText("Red Square");
        RedSquareBtn.setOpaque(false);
        RedSquareBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedSquareBtnActionPerformed(evt);
            }
        });
        jPanel1.add(RedSquareBtn);
        RedSquareBtn.setBounds(200, 240, 110, 20);

        GreenCircleBtn.setBackground(new java.awt.Color(255, 255, 255));
        GreenCircleBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        GreenCircleBtn.setForeground(new java.awt.Color(0, 204, 0));
        GreenCircleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Green Circle.png"))); // NOI18N
        GreenCircleBtn.setText("Green Circle");
        GreenCircleBtn.setOpaque(false);
        GreenCircleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreenCircleBtnActionPerformed(evt);
            }
        });
        jPanel1.add(GreenCircleBtn);
        GreenCircleBtn.setBounds(30, 240, 110, 20);

        rCircleBtn.setBackground(new java.awt.Color(255, 255, 255));
        rCircleBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rCircleBtn.setForeground(new java.awt.Color(255, 0, 51));
        rCircleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Red Circle.png"))); // NOI18N
        rCircleBtn.setText("Red Circle");
        rCircleBtn.setOpaque(false);
        rCircleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCircleBtnActionPerformed(evt);
            }
        });
        jPanel1.add(rCircleBtn);
        rCircleBtn.setBounds(30, 210, 110, 20);

        displayLbl.setBackground(new java.awt.Color(102, 255, 255));
        displayLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        displayLbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(displayLbl);
        displayLbl.setBounds(1, 274, 460, 15);

        bSquareBtn.setBackground(new java.awt.Color(255, 255, 255));
        bSquareBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bSquareBtn.setForeground(new java.awt.Color(0, 153, 255));
        bSquareBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Blue Square.png"))); // NOI18N
        bSquareBtn.setText("Blue Square");
        bSquareBtn.setOpaque(false);
        bSquareBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSquareBtnActionPerformed(evt);
            }
        });
        jPanel1.add(bSquareBtn);
        bSquareBtn.setBounds(200, 210, 110, 20);

        bcGroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bGround.jpg"))); // NOI18N
        jPanel1.add(bcGroundLbl);
        bcGroundLbl.setBounds(0, 0, 460, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rCircleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCircleBtnActionPerformed
        // TODO add your handling code here:

        //If statement to check if image matches.
        if (myButton.ImageName.equalsIgnoreCase("Red Circle")
                || myButton1.ImageName.equalsIgnoreCase("Red Circle")) {

            displayLbl.setText("WELL DONE! YOU ARE CORRECT!");
            score += 5;
            score1Lbl.setText(Integer.toString(score));
            ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/circle-blue.png"));
            ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/images/triangle-green.png"));
            myButton.setIcon(icon);
            myButton.ImageName = "Blue Circle";
            myButton1.setIcon(icon1);
            myButton1.ImageName = "Green Triangle";

        } else {
            displayLbl.setText("SORRY! YOU ARE WRONG!");
            score -= 5;
            score1Lbl.setText(Integer.toString(score));
            ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/circle-blue.png"));
            ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/images/triangle-green.png"));
            myButton.setIcon(icon);
            myButton.ImageName = "Blue Circle";
            myButton1.setIcon(icon1);
            myButton1.ImageName = "Green Triangle";

        }
        obj.setGamercore(score);
        updateScore(obj);

    }//GEN-LAST:event_rCircleBtnActionPerformed

    private void bSquareBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSquareBtnActionPerformed
        // TODO add your handling code here:

        //If statement to check if image matches.
        if (myButton.ImageName.equalsIgnoreCase("Blue Square")
                || myButton1.ImageName.equalsIgnoreCase("Blue Square")) {

            displayLbl.setText("WELL DONE! YOU ARE CORRECT!");
            score += 5;
            score1Lbl.setText(Integer.toString(score));
            JOptionPane.showMessageDialog(null,"Your Score for level 1 = " + score + "\n" + "Level 2 will now Start!");
            GameGUI2 a = new GameGUI2();
            a.setScore(score);
            a.setVisible(true);
            dispose();

        } else {
            displayLbl.setText("SORRY! YOU ARE WRONG!");
            score -= 5;
            score1Lbl.setText(Integer.toString(score));
            JOptionPane.showMessageDialog(null,"Your Score for level 1 = " + score + "\n" + "Level 2 will now Start!");

            GameGUI2 a = new GameGUI2();
            a.setVisible(true);
            dispose();

        }

        obj.setGamercore(score);
        updateScore(obj);
    }//GEN-LAST:event_bSquareBtnActionPerformed

    private void GreenCircleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreenCircleBtnActionPerformed
        // TODO add your handling code here:
        //If statement to check if image matches.

        if (myButton.ImageName.equalsIgnoreCase("Blue Circle")
                || myButton1.ImageName.equalsIgnoreCase("Blue Circle")) {

            displayLbl.setText("WELL DONE! YOU ARE CORRECT!");
            score += 5;
            score1Lbl.setText(Integer.toString(score));
            ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/circle-blue.png"));
            ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/images/triangle-green.png"));
            myButton.setIcon(icon);
            myButton.ImageName = "Blue Circle";
            myButton1.setIcon(icon1);
            myButton1.ImageName = "Green Triangle";

        } else {
            displayLbl.setText("SORRY! YOU ARE WRONG!");
            score -= 5;
            score1Lbl.setText(Integer.toString(score));
            ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/circle-blue.png"));
            ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/images/triangle-green.png"));
            myButton.setIcon(icon);
            myButton.ImageName = "Blue Circle";
            myButton1.setIcon(icon1);
            myButton1.ImageName = "Green Triangle";

        }
        obj.setGamercore(score);
        updateScore(obj);

    }//GEN-LAST:event_GreenCircleBtnActionPerformed

    private void RedSquareBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedSquareBtnActionPerformed
        // TODO add your handling code here:
        //If statement to check if image matches.
        if (myButton.ImageName.equalsIgnoreCase("Red Square")
                || myButton1.ImageName.equalsIgnoreCase("Red Square")) {
            displayLbl.setText("WELL DONE! YOU ARE CORRECT!");
            score += 5;
            score1Lbl.setText(Integer.toString(score));
            ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/square-blue.png"));
            ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/images/sphere-orange.png"));
            myButton.setIcon(icon);
            myButton.ImageName = "Blue Square";
            myButton1.setIcon(icon1);
            myButton1.ImageName = "Orange Sphere";

        } else {
            displayLbl.setText("SORRY! YOU ARE WRONG!");
            score -= 5;
            score1Lbl.setText(Integer.toString(score));
            ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/square-blue.png"));
            ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/images/sphere-orange.png"));
            myButton.setIcon(icon);
            myButton.ImageName = "Blue Square";
            myButton1.setIcon(icon1);
            myButton1.ImageName = "Orange Sphere";

        }

        obj.setGamercore(score);
        updateScore(obj);
    }//GEN-LAST:event_RedSquareBtnActionPerformed

    private void gTriangleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gTriangleBtnActionPerformed
        // TODO add your handling code here:
        //If statement to check if image matches.
        if (myButton.ImageName.equalsIgnoreCase("Green Triangle")
                || myButton1.ImageName.equalsIgnoreCase("Green Triangle")) {
            displayLbl.setText("WELL DONE! YOU ARE CORRECT!");
            score += 5;
            score1Lbl.setText(Integer.toString(score));
            ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/square-blue.png"));
            ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/images/sphere-orange.png"));
            myButton.setIcon(icon);
            myButton.ImageName = "Blue Square";
            myButton1.setIcon(icon1);
            myButton1.ImageName = "Orange Sphere";

        } else {
            displayLbl.setText("SORRY! YOU ARE WRONG!");
            score -= 5;
            score1Lbl.setText(Integer.toString(score));
            ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/square-blue.png"));
            ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/images/sphere-orange.png"));
            myButton.setIcon(icon);
            myButton.ImageName = "Blue Square";
            myButton1.setIcon(icon1);
            myButton1.ImageName = "Orange Sphere";

        }
        obj.setGamercore(score);
        updateScore(obj);


    }//GEN-LAST:event_gTriangleBtnActionPerformed

    private void PurpleTriangleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurpleTriangleBtnActionPerformed
        // TODO add your handling code here:
        //If statement to check if image matches.

        if (myButton.ImageName.equalsIgnoreCase("Purple Triangle")
                || myButton1.ImageName.equalsIgnoreCase("Purple Triangle")) {
            displayLbl.setText("WELL DONE! YOU ARE CORRECT!");
            score += 5;
            score1Lbl.setText(Integer.toString(score));
            ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/square-blue.png"));
            ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/images/sphere-blue.png"));
            myButton.setIcon(icon);
            myButton.ImageName = "Blue Square";
            myButton1.setIcon(icon1);
            myButton1.ImageName = "Red Circle";

        } else {
            displayLbl.setText("SORRY! YOU ARE WRONG!");
            score -= 5;
            score1Lbl.setText(Integer.toString(score));
            ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/square-blue.png"));
            ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/images/sphere-blue.png"));
            myButton.setIcon(icon);
            myButton.ImageName = "Blue Square";
            myButton1.setIcon(icon1);
            myButton1.ImageName = "Blue Circle";

        }
        obj.setGamercore(score);
        updateScore(obj);


    }//GEN-LAST:event_PurpleTriangleBtnActionPerformed

    private void EndBTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndBTnActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
    String name = JOptionPane.showInputDialog(frame, "Please enter name");
    String query =  "UPDATE player SET gamerscore = '"+score+"'  WHERE gamertag = '"+name+"';"; 
        boolean upd = manager.UPDATE_QUERY(query);
    if(upd == true){
        JOptionPane.showMessageDialog(null,"saved successfully");
        HomeGUI c= new HomeGUI();
        c.setVisible(true);
        dispose();
        
    }
    else{
         JOptionPane.showMessageDialog(null,"saving failed! please try again");
        
    }
    
               HomeGUI d = new HomeGUI();
               d.setVisible(true);
               this.dispose();
        JOptionPane.showMessageDialog(null, "Your Score is " + score);
        HomeGUI c= new HomeGUI();
        c.setVisible(true);
        dispose();

        obj.setGamercore(score);
        updateScore(obj);

    }//GEN-LAST:event_EndBTnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameGUI2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EndBTn;
    private javax.swing.JButton GreenCircleBtn;
    private javax.swing.JButton PurpleTriangleBtn;
    private javax.swing.JButton RedSquareBtn;
    private javax.swing.JLabel TitleBtn;
    private javax.swing.JButton bSquareBtn;
    private javax.swing.JLabel bcGroundLbl;
    private javax.swing.JLabel displayLbl;
    private javax.swing.JButton gTriangleBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLayeredPane lPane;
    private javax.swing.JLayeredPane lPane2;
    private javax.swing.JButton rCircleBtn;
    public javax.swing.JLabel score1Lbl;
    private javax.swing.JLabel scoreLbl;
    // End of variables declaration//GEN-END:variables
}
