package shapes;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author x13114352
 */
public class GameGUI2 extends javax.swing.JFrame {

    CustButton myButton = new CustButton();
    CustButton myButton1 = new CustButton();
    CustButton myButton2 = new CustButton();

    int score = 0;
    Player obj = new Player();

    Connection conn;
    DBManager manager;

    String dbServer = "jdbc:mysql://mysql1.gear.host/";
    String dbName = "shapersdb";
    String dbUser = "shapers";
    String dbPass = "shapers!";
    String driver = "com.mysql.jdbc.Driver";

    public void setScore(int score){
        this.score=score;
        score2Lbl.setText(score+"");
    }
    /**
     * Creates new form gameGUI
     */
    public GameGUI2() {
        super("Shapes Game");
        initComponents();
        manager = new DBManager();

        try {
            conn = DriverManager.getConnection(dbServer + dbName, dbUser, dbPass);
            manager.setConn(conn);
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());

        }

        //imageIcon 
        ImageIcon image = new ImageIcon(getClass().getResource("/images/sphere-red.png"));

        myButton.ImageName = "Red Circle";
        myButton.setName("circleLb");
        myButton.setBounds(0, 0, 190, 150);
        myButton.setOpaque(false);
        myButton.setContentAreaFilled(false);
        myButton.setBorderPainted(false);
        myButton.setIcon(image);
        lPane.add(myButton);

        ImageIcon image2 = new ImageIcon(getClass().getResource("/images/square-green.png"));

        myButton1.ImageName = "Green Square";
        myButton1.setName("circleLb");
        myButton1.setBounds(0, 0, 190, 150);
        myButton1.setOpaque(false);
        myButton1.setContentAreaFilled(false);
        myButton1.setBorderPainted(false);
        myButton1.setIcon(image2);
        lPane2.add(myButton1);

        ImageIcon image3 = new ImageIcon(getClass().getResource("/images/triangle-green.png"));

        myButton2.ImageName = "Triangle Green";
        myButton2.setName("circleLb");
        myButton2.setBounds(0, 0, 190, 150);
        myButton2.setOpaque(false);
        myButton2.setContentAreaFilled(false);
        myButton2.setBorderPainted(false);
        myButton2.setIcon(image3);
        lPane3.add(myButton2);
    }

    public void setPlayer(Player p) {
        this.obj = p;
    }

    public void updateScore(Player s) {
        String query = "UPDATE Player SET gamerscore = " + s.getGamercore() + ""
                + " where pid=" + s.getPid() + ";";
        boolean upd = manager.UPDATE_QUERY(query);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TitleBtn = new javax.swing.JLabel();
        EndBTn = new javax.swing.JButton();
        lPane3 = new javax.swing.JLayeredPane();
        lPane2 = new javax.swing.JLayeredPane();
        scoreLbl = new javax.swing.JLabel();
        score2Lbl = new javax.swing.JLabel();
        lPane = new javax.swing.JLayeredPane();
        Button6Btn = new javax.swing.JButton();
        Button5Btn = new javax.swing.JButton();
        Button4Btn = new javax.swing.JButton();
        Button2Btn = new javax.swing.JButton();
        Button1Btn = new javax.swing.JButton();
        displayLbl = new javax.swing.JLabel();
        Button3Btn = new javax.swing.JButton();
        bcGroundLbl = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(630, 630));
        jPanel1.setLayout(null);

        TitleBtn.setBackground(new java.awt.Color(255, 255, 255));
        TitleBtn.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        TitleBtn.setText("Level 2");
        jPanel1.add(TitleBtn);
        TitleBtn.setBounds(190, 20, 120, 30);

        EndBTn.setBackground(new java.awt.Color(255, 255, 255));
        EndBTn.setText("End Game");
        EndBTn.setOpaque(false);
        EndBTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndBTnActionPerformed(evt);
            }
        });
        jPanel1.add(EndBTn);
        EndBTn.setBounds(350, 270, 100, 23);

        javax.swing.GroupLayout lPane3Layout = new javax.swing.GroupLayout(lPane3);
        lPane3.setLayout(lPane3Layout);
        lPane3Layout.setHorizontalGroup(
            lPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        lPane3Layout.setVerticalGroup(
            lPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel1.add(lPane3);
        lPane3.setBounds(300, 70, 150, 110);

        javax.swing.GroupLayout lPane2Layout = new javax.swing.GroupLayout(lPane2);
        lPane2.setLayout(lPane2Layout);
        lPane2Layout.setHorizontalGroup(
            lPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        lPane2Layout.setVerticalGroup(
            lPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel1.add(lPane2);
        lPane2.setBounds(30, 80, 140, 110);

        scoreLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        scoreLbl.setText("Score:");
        jPanel1.add(scoreLbl);
        scoreLbl.setBounds(320, 10, 70, 40);

        score2Lbl.setBackground(new java.awt.Color(0, 0, 0));
        score2Lbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(score2Lbl);
        score2Lbl.setBounds(400, 20, 40, 20);

        lPane.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout lPaneLayout = new javax.swing.GroupLayout(lPane);
        lPane.setLayout(lPaneLayout);
        lPaneLayout.setHorizontalGroup(
            lPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        lPaneLayout.setVerticalGroup(
            lPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(lPane);
        lPane.setBounds(190, 90, 140, 100);

        Button6Btn.setBackground(new java.awt.Color(255, 255, 255));
        Button6Btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button6Btn.setForeground(new java.awt.Color(204, 0, 0));
        Button6Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Blue Square.png"))); // NOI18N
        Button6Btn.setText("Blue Square");
        Button6Btn.setOpaque(false);
        Button6Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Button6Btn);
        Button6Btn.setBounds(340, 240, 110, 20);

        Button5Btn.setBackground(new java.awt.Color(255, 255, 255));
        Button5Btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button5Btn.setForeground(new java.awt.Color(255, 102, 0));
        Button5Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Orange Triangle.png"))); // NOI18N
        Button5Btn.setText("Orange Triangle");
        Button5Btn.setOpaque(false);
        Button5Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Button5Btn);
        Button5Btn.setBounds(340, 210, 110, 20);

        Button4Btn.setBackground(new java.awt.Color(255, 255, 255));
        Button4Btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button4Btn.setForeground(new java.awt.Color(0, 204, 51));
        Button4Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Green Square.png"))); // NOI18N
        Button4Btn.setText("Green Square");
        Button4Btn.setOpaque(false);
        Button4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Button4Btn);
        Button4Btn.setBounds(200, 240, 110, 20);

        Button2Btn.setBackground(new java.awt.Color(255, 255, 255));
        Button2Btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button2Btn.setForeground(new java.awt.Color(0, 153, 255));
        Button2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Blue Circle.png"))); // NOI18N
        Button2Btn.setText("Blue Circle");
        Button2Btn.setOpaque(false);
        Button2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Button2Btn);
        Button2Btn.setBounds(40, 240, 110, 20);

        Button1Btn.setBackground(new java.awt.Color(255, 255, 255));
        Button1Btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button1Btn.setForeground(new java.awt.Color(255, 255, 0));
        Button1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Yellow Circle.png"))); // NOI18N
        Button1Btn.setText("Yellow Circle");
        Button1Btn.setOpaque(false);
        Button1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Button1Btn);
        Button1Btn.setBounds(40, 210, 110, 20);

        displayLbl.setBackground(new java.awt.Color(102, 255, 255));
        displayLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        displayLbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(displayLbl);
        displayLbl.setBounds(1, 274, 460, 15);

        Button3Btn.setBackground(new java.awt.Color(255, 255, 255));
        Button3Btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Button3Btn.setForeground(new java.awt.Color(204, 0, 0));
        Button3Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Red Cylinder.png"))); // NOI18N
        Button3Btn.setText("Red Cylinder");
        Button3Btn.setOpaque(false);
        Button3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Button3Btn);
        Button3Btn.setBounds(200, 210, 110, 20);

        bcGroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bGround.jpg"))); // NOI18N
        jPanel1.add(bcGroundLbl);
        bcGroundLbl.setBounds(0, 0, 460, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1BtnActionPerformed
        // TODO add your handling code here:

        //If statement to check if image matches.
        if (myButton.ImageName.equalsIgnoreCase("Yellow Circle")
                || myButton1.ImageName.equalsIgnoreCase("Yellow Circle")
                || myButton2.ImageName.equalsIgnoreCase("Yellow Circle")) {

            displayLbl.setText("WELL DONE! YOU ARE CORRECT!");
            score += 5;
            score2Lbl.setText(Integer.toString(score));
            ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/triangle-yellow.png"));
            ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/images/circle-red.png"));
            ImageIcon icon2 = new ImageIcon(this.getClass().getResource("/images/square-blue.png"));
            myButton.setIcon(icon);
            myButton.ImageName = "Yellow Triangle";
            myButton1.setIcon(icon1);
            myButton1.ImageName = "Red Circle";
            myButton2.setIcon(icon2);
            myButton2.ImageName = "Blue Square";

        } else {
            displayLbl.setText("SORRY! YOU ARE WRONG!");
            score -= 5;
            score2Lbl.setText(Integer.toString(score));
            ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/triangle-yellow.png"));
            ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/images/circle-red.png"));
            ImageIcon icon2 = new ImageIcon(this.getClass().getResource("/images/square-blue.png"));
            myButton.setIcon(icon);
            myButton.ImageName = "Yellow Triangle";
            myButton1.setIcon(icon1);
            myButton1.ImageName = "Red Circle";
            myButton2.setIcon(icon2);
            myButton2.ImageName = "Blue Square";

        }
        obj.setGamercore(score);
        updateScore(obj);

    }//GEN-LAST:event_Button1BtnActionPerformed

    private void Button3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3BtnActionPerformed
        // TODO add your handling code here:

        //If statement to check if image matches.
        if (myButton.ImageName.equalsIgnoreCase("Red Cylinder")
                || myButton1.ImageName.equalsIgnoreCase("Red Cylinder")
                || myButton2.ImageName.equalsIgnoreCase("Red Cylinder")) {

            displayLbl.setText("WELL DONE! YOU ARE CORRECT!");
            score += 5;
            score2Lbl.setText(Integer.toString(score));
            ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/triangle-yellow.png"));
            ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/images/circle-red.png"));
            ImageIcon icon2 = new ImageIcon(this.getClass().getResource("/images/square-blue.png"));
            myButton.setIcon(icon);
            myButton.ImageName = "Yellow Triangle";
            myButton1.setIcon(icon1);
            myButton1.ImageName = "Red Circle";
            myButton2.setIcon(icon2);
            myButton2.ImageName = "Blue Square";

        } else {
            displayLbl.setText("SORRY! YOU ARE WRONG!");
            score -= 5;
            score2Lbl.setText(Integer.toString(score));
            ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/triangle-yellow.png"));
            ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/images/circle-red.png"));
            ImageIcon icon2 = new ImageIcon(this.getClass().getResource("/images/square-blue.png"));
            myButton.setIcon(icon);
            myButton.ImageName = "Yellow Triangle";
            myButton1.setIcon(icon1);
            myButton1.ImageName = "Red Circle";
            myButton2.setIcon(icon2);
            myButton2.ImageName = "Blue Square";
        }

        obj.setGamercore(score);
        updateScore(obj);
    }//GEN-LAST:event_Button3BtnActionPerformed

    private void Button2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2BtnActionPerformed
        // TODO add your handling code here:
        //If statement to check if image matches.

        if (myButton.ImageName.equalsIgnoreCase("Blue Circle")
                || myButton2.ImageName.equalsIgnoreCase("Blue Circle")
                || myButton1.ImageName.equalsIgnoreCase("Blue Circle")) {

            displayLbl.setText("WELL DONE! YOU ARE CORRECT!");
            score += 5;
            score2Lbl.setText(Integer.toString(score));
            JOptionPane.showMessageDialog(null, "Your Score for level 2 = " + score + "\n" + "Level 3 will now Start!");
            GameGUI3 a = new GameGUI3();
            a.setScore(score);
            a.setVisible(true);
            dispose();

        } else {
             ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/triangle-yellow.png"));
            ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/images/circle-red.png"));
            ImageIcon icon2 = new ImageIcon(this.getClass().getResource("/images/square-blue.png"));
            myButton.setIcon(icon);
            myButton.ImageName = "Yellow Triangle";
            myButton1.setIcon(icon1);
            myButton1.ImageName = "Red Circle";
            myButton2.setIcon(icon2);
            myButton2.ImageName = "Blue Square";
        }
        obj.setGamercore(score);
        updateScore(obj);

    }//GEN-LAST:event_Button2BtnActionPerformed

    private void Button4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4BtnActionPerformed
        // TODO add your handling code here:
        //If statement to check if image matches.
        if (myButton.ImageName.equalsIgnoreCase("Green Square")
                || myButton1.ImageName.equalsIgnoreCase("Green Square")
                || myButton2.ImageName.equalsIgnoreCase("Green Square")) {
            displayLbl.setText("WELL DONE! YOU ARE CORRECT!");
            score += 5;
            score2Lbl.setText(Integer.toString(score));
            ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/triangle-yellow.png"));
            ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/images/circle-red.png"));
            ImageIcon icon2 = new ImageIcon(this.getClass().getResource("/images/square-blue.png"));
            myButton.setIcon(icon);
            myButton.ImageName = "Yellow Triangle";
            myButton1.setIcon(icon1);
            myButton1.ImageName = "Red Circle";
            myButton2.setIcon(icon2);
            myButton2.ImageName = "Blue Square";
        } else {
            displayLbl.setText("SORRY! YOU ARE WRONG!");
            score -= 5;
            score2Lbl.setText(Integer.toString(score));
            ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/triangle-yellow.png"));
            ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/images/circle-blue.png"));
            ImageIcon icon2 = new ImageIcon(this.getClass().getResource("/images/cone-green.png"));
            myButton.setIcon(icon);
            myButton.ImageName = "Yellow Triangle";
            myButton1.setIcon(icon1);
            myButton1.ImageName = "Blue Circle";
            myButton2.setIcon(icon2);
            myButton2.ImageName = "Green Cone";
        }

        obj.setGamercore(score);
        updateScore(obj);
    }//GEN-LAST:event_Button4BtnActionPerformed

    private void Button6BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6BtnActionPerformed
        // TODO add your handling code here:
        //If statement to check if image matches.
        if (myButton.ImageName.equalsIgnoreCase("Blue Square")
                || myButton1.ImageName.equalsIgnoreCase("Blue Square")
                || myButton2.ImageName.equalsIgnoreCase("Blue Square")) {
            displayLbl.setText("WELL DONE! YOU ARE CORRECT!");
            score += 5;
            score2Lbl.setText(Integer.toString(score));
            ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/triangle-green.png"));
            ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/images/circle-blue.png"));
            ImageIcon icon2 = new ImageIcon(this.getClass().getResource("/images/cone-black.png"));
            myButton.setIcon(icon);
            myButton.ImageName = "Green Triangle";
            myButton1.setIcon(icon1);
            myButton1.ImageName = "Blue Circle";
            myButton2.setIcon(icon2);
            myButton2.ImageName = "Black Cone";
        } else {
            displayLbl.setText("SORRY! YOU ARE WRONG!");
            score -= 5;
            score2Lbl.setText(Integer.toString(score));
            ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/triangle-green.png"));
            ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/images/circle-blue.png"));
            ImageIcon icon2 = new ImageIcon(this.getClass().getResource("/images/cone-Black.png"));
            myButton.setIcon(icon);
            myButton.ImageName = "Green Triangle";
            myButton1.setIcon(icon1);
            myButton1.ImageName = "Blue Circle";
            myButton2.setIcon(icon2);
            myButton2.ImageName = "Black Cone";
        }
        obj.setGamercore(score);
        updateScore(obj);


    }//GEN-LAST:event_Button6BtnActionPerformed

    private void Button5BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5BtnActionPerformed
        // TODO add your handling code here:
        //If statement to check if image matches.

        if (myButton.ImageName.equalsIgnoreCase("Orange Triangle")
                || myButton1.ImageName.equalsIgnoreCase("Orange Triangle")
                || myButton2.ImageName.equalsIgnoreCase("Orange Triangle")) {
            displayLbl.setText("WELL DONE! YOU ARE CORRECT!");
            score += 5;
            score2Lbl.setText(Integer.toString(score));
            ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/triangle-yellow.png"));
            ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/images/circle-red.png"));
            ImageIcon icon2 = new ImageIcon(this.getClass().getResource("/images/square-blue.png"));
            myButton.setIcon(icon);
            myButton.ImageName = "Yellow Triangle";
            myButton1.setIcon(icon1);
            myButton1.ImageName = "Red Circle";
            myButton2.setIcon(icon2);
            myButton2.ImageName = "Blue Square";

        } else {
            displayLbl.setText("SORRY! YOU ARE WRONG!");
            score -= 5;
            score2Lbl.setText(Integer.toString(score));
            ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/triangle-yellow.png"));
            ImageIcon icon1 = new ImageIcon(this.getClass().getResource("/images/circle-red.png"));
            ImageIcon icon2 = new ImageIcon(this.getClass().getResource("/images/square-blue.png"));
            myButton.setIcon(icon);
            myButton.ImageName = "Yellow Triangle";
            myButton1.setIcon(icon1);
            myButton1.ImageName = "Red Circle";
            myButton2.setIcon(icon2);
            myButton2.ImageName = "Blue Square";
        }
        obj.setGamercore(score);
        updateScore(obj);


    }//GEN-LAST:event_Button5BtnActionPerformed

    private void EndBTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndBTnActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
    String name = JOptionPane.showInputDialog(frame, "Please enter name");
    String query =  "UPDATE player SET gamerscore = '"+score+"'  WHERE gamertag = '"+name+"';"; 
        boolean upd = manager.UPDATE_QUERY(query);
    if(upd == true){
        JOptionPane.showMessageDialog(null,"saved successfully");
        HomeGUI c= new HomeGUI();
        c.setVisible(true);
        dispose();
        
    }
    else{
         JOptionPane.showMessageDialog(null,"saving failed! please try again");
    }
        
//        JOptionPane.showMessageDialog(null, "Your Score for level 2 is " + score);
//        HomeGUI c= new HomeGUI();
//        c.setVisible(true);
//        dispose();


        obj.setGamercore(score);
        updateScore(obj);


    }//GEN-LAST:event_EndBTnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameGUI2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button1Btn;
    private javax.swing.JButton Button2Btn;
    private javax.swing.JButton Button3Btn;
    private javax.swing.JButton Button4Btn;
    private javax.swing.JButton Button5Btn;
    private javax.swing.JButton Button6Btn;
    private javax.swing.JButton EndBTn;
    private javax.swing.JLabel TitleBtn;
    private javax.swing.JLabel bcGroundLbl;
    private javax.swing.JLabel displayLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLayeredPane lPane;
    private javax.swing.JLayeredPane lPane2;
    private javax.swing.JLayeredPane lPane3;
    private javax.swing.JLabel score2Lbl;
    private javax.swing.JLabel scoreLbl;
    // End of variables declaration//GEN-END:variables
}
