package shapes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x12724145
 */
public class HomeGUI extends javax.swing.JFrame {
    
     int score = 0;
    Player obj = new Player();

    Connection conn;
    DBManager manager;

    String dbServer = "jdbc:mysql://mysql1.gear.host/";
    String dbName = "shapersdb";
    String dbUser = "shapers";
    String dbPass = "shapers!";
    String driver = "com.mysql.jdbc.Driver";
    private Player currPlayer;

    /**
     * Creates new form aboutGUI
     */
    public HomeGUI() {
        super("Shapes Game");
        initComponents();
                manager = new DBManager();

        try {
            conn = DriverManager.getConnection(dbServer + dbName, dbUser, dbPass);
            manager.setConn(conn);
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());

        }
        
        
    }
    public void setPlayer(Player p) {
        this.obj = p;
    }

    public void updateScore(Player s) {
        String query = "UPDATE Player SET gamerscore = " + s.getGamercore() + ""
                + " where pid=" + s.getPid() + ";";
        boolean upd = manager.UPDATE_QUERY(query);
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        NewGameBTN = new javax.swing.JButton();
        InstructionsBTN = new javax.swing.JButton();
        ScoresBTN = new javax.swing.JButton();
        ExitBTN = new javax.swing.JButton();
        AboutBTN = new javax.swing.JButton();
        imageLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NewGameBTN.setBackground(new java.awt.Color(255, 255, 255));
        NewGameBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finishThirdSign.png"))); // NOI18N
        NewGameBTN.setBorderPainted(false);
        NewGameBTN.setContentAreaFilled(false);
        NewGameBTN.setFocusPainted(false);
        NewGameBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGameBTNActionPerformed(evt);
            }
        });
        jLayeredPane1.add(NewGameBTN);
        NewGameBTN.setBounds(70, 140, 110, 90);

        InstructionsBTN.setBackground(new java.awt.Color(255, 255, 255));
        InstructionsBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/infoSign.png"))); // NOI18N
        InstructionsBTN.setBorderPainted(false);
        InstructionsBTN.setContentAreaFilled(false);
        InstructionsBTN.setFocusPainted(false);
        InstructionsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstructionsBTNActionPerformed(evt);
            }
        });
        jLayeredPane1.add(InstructionsBTN);
        InstructionsBTN.setBounds(10, 90, 130, 100);

        ScoresBTN.setBackground(new java.awt.Color(255, 255, 255));
        ScoresBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finishedFirstEditedSign.png"))); // NOI18N
        ScoresBTN.setBorderPainted(false);
        ScoresBTN.setContentAreaFilled(false);
        ScoresBTN.setFocusPainted(false);
        ScoresBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScoresBTNActionPerformed(evt);
            }
        });
        jLayeredPane1.add(ScoresBTN);
        ScoresBTN.setBounds(100, 60, 180, 140);

        ExitBTN.setBackground(new java.awt.Color(255, 255, 255));
        ExitBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exitSign.png"))); // NOI18N
        ExitBTN.setBorderPainted(false);
        ExitBTN.setContentAreaFilled(false);
        ExitBTN.setFocusPainted(false);
        ExitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBTNActionPerformed(evt);
            }
        });
        jLayeredPane1.add(ExitBTN);
        ExitBTN.setBounds(60, 180, 130, 200);

        AboutBTN.setBackground(new java.awt.Color(255, 255, 255));
        AboutBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finishedFourthSign.png"))); // NOI18N
        AboutBTN.setBorderPainted(false);
        AboutBTN.setContentAreaFilled(false);
        AboutBTN.setFocusPainted(false);
        AboutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutBTNActionPerformed(evt);
            }
        });
        jLayeredPane1.add(AboutBTN);
        AboutBTN.setBounds(130, 180, 100, 90);

        imageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aboutPageBG.jpg"))); // NOI18N
        jLayeredPane1.add(imageLbl);
        imageLbl.setBounds(0, 0, 450, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NewGameBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewGameBTNActionPerformed
        GameGUI a = new GameGUI();
        a.setPlayer(currPlayer);
        a.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_NewGameBTNActionPerformed

    private void ScoresBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScoresBTNActionPerformed
      LeaderBrdGUI L = new LeaderBrdGUI();
       L.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_ScoresBTNActionPerformed

    private void ExitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBTNActionPerformed
                dispose();
    }//GEN-LAST:event_ExitBTNActionPerformed

    private void InstructionsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstructionsBTNActionPerformed
        InfoGUI I= new InfoGUI();
        I.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InstructionsBTNActionPerformed

    private void AboutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutBTNActionPerformed
        AboutGUI a= new AboutGUI();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AboutBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new HomeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutBTN;
    private javax.swing.JButton ExitBTN;
    private javax.swing.JButton InstructionsBTN;
    private javax.swing.JButton NewGameBTN;
    private javax.swing.JButton ScoresBTN;
    private javax.swing.JLabel imageLbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
